#! /usr/bin/env python
# encoding: utf-8

import glob
DIRS = "iterators experimental"

exclude=\
    ["list.cpp"]

def build(bld):
    cpp_files=\
        set(
            file.split("/")[-1]
            for file in glob.glob(
                    bld.path.abspath() + "/*.cpp")
        ).difference(exclude)
    INCLUDES=\
        ["../../" + x for x in bld.env.INCLUDES_REL]\
        + bld.env.INCLUDES_ABS
    bld.objects(
        source = cpp_files,
        target = "TestContainers",
        cxxflags = bld.env.CXXFLAGS,
        includes = INCLUDES,
        lib = bld.env.LDFLAGS_N)
    bld.recurse(
        DIRS)

