#! /usr/bin/env python
# encoding: utf-8

#from waflib.Configure import conf
import glob, os

DIRS = "utils containers database"

def build(bld):
        bld.recurse(DIRS)
        INCLUDES = ["../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS

        bld.program(
                source = "category.cpp",
                use = ["containers", "database", "utils"],
                target = "ctgtest",
                stlib = bld.env.STLIB, #static lib - needed if not default
                cxxflags = bld.env.CXXFLAGS,
                includes = INCLUDES,
                lib = bld.env.LDFLAGS_N
        )

        bld.recurse(DIRS)
