#! /usr/bin/env python
# encoding utf-8

DIRS = ""

def build(bld):
    INCLUDES=\
        ["../" + x for x in bld.env.INCLUDES_REL]\
        + bld.env.INCLUDES_ABS
    bld.program(
        source="main.cpp",
        use=["TestContainers",
             "TestIterators",
             "TestDatabase",
             "TestUtils",
             "TestExperimental"],
        target="test",
        stlib=bld.env.STLIB,
        cxxflags=bld.env.CXXFLAGS,
        includes=INCLUDES,
        lib=bld.env.LDFLAGS_N)

    if bld.cmd != "clean":
        from waflib import Logs
        bld.logger=\
            Logs.make_logger(
                "test.log",
                "build")
    else:
        bld.logger = None
    bld.recurse(DIRS)
